export const orderStatusStyles = {
  Delivered: 'bg-emerald-50 text-emerald-700',
  Shipped: 'bg-blue-50 text-blue-700',
  Packed: 'bg-amber-50 text-amber-700',
  Processing: 'bg-violet-50 text-violet-700',
  Pending: 'bg-slate-100 text-slate-700',
}

export const paymentStatusStyles = {
  Paid: 'bg-emerald-50 text-emerald-700',
  Partial: 'bg-amber-50 text-amber-700',
  Unpaid: 'bg-red-50 text-red-700',
}

export const ordersData = [
  {
    id: 'QB-ORD-2401',
    customerId: 'QB-CUST-E60786-001',
    customer: 'Rahul Traders',
    phone: '9876543210',
    city: 'Pune',
    state: 'Maharashtra',
    placedOn: '2026-06-08',
    deliveryDate: '2026-06-12',
    itemCount: 18,
    amount: 48200,
    status: 'Delivered',
    paymentStatus: 'Paid',
    salesChannel: 'Wholesale Call',
    shippingAddress: 'MG Road, Pune, Maharashtra, 411001',
    notes: 'Bulk restock for school bag collection.',
    items: [
      { sku: 'QB-SCH-101', name: 'School Backpack Pro', quantity: 8, price: 1850 },
      { sku: 'QB-TRV-204', name: 'Travel Duffel Max', quantity: 4, price: 2950 },
      { sku: 'QB-LTP-044', name: 'Laptop Office Bag', quantity: 6, price: 2100 },
    ],
  },
  {
    id: 'QB-ORD-2397',
    customerId: 'QB-CUST-A11340-004',
    customer: 'Madina Bags',
    phone: '76634944949',
    city: 'Sangli',
    state: 'Maharashtra',
    placedOn: '2026-06-07',
    deliveryDate: '2026-06-11',
    itemCount: 12,
    amount: 31950,
    status: 'Shipped',
    paymentStatus: 'Partial',
    salesChannel: 'WhatsApp Order',
    shippingAddress: 'Station Road, Sangli, Maharashtra, 416416',
    notes: 'Customer requested mixed colors where available.',
    items: [
      { sku: 'QB-HND-302', name: 'Classic Handbag', quantity: 5, price: 1750 },
      { sku: 'QB-LTP-044', name: 'Laptop Office Bag', quantity: 3, price: 2100 },
      { sku: 'QB-TRV-118', name: 'Compact Trolley Bag', quantity: 4, price: 3125 },
    ],
  },
  {
    id: 'QB-ORD-2386',
    customerId: 'QB-CUST-R50412-003',
    customer: 'City Retail House',
    phone: '9988776655',
    city: 'Mumbai',
    state: 'Maharashtra',
    placedOn: '2026-06-06',
    deliveryDate: '2026-06-10',
    itemCount: 9,
    amount: 21400,
    status: 'Packed',
    paymentStatus: 'Paid',
    salesChannel: 'Store Pickup',
    shippingAddress: 'Dadar West, Mumbai, Maharashtra, 400028',
    notes: 'Pickup expected in the afternoon slot.',
    items: [
      { sku: 'QB-SCH-087', name: 'Kids School Bag', quantity: 4, price: 1450 },
      { sku: 'QB-HND-155', name: 'Mini Sling Bag', quantity: 3, price: 1200 },
      { sku: 'QB-TRV-204', name: 'Travel Duffel Max', quantity: 2, price: 4950 },
    ],
  },
  {
    id: 'QB-ORD-2379',
    customerId: 'QB-CUST-T22001-009',
    customer: 'Trendz Corner',
    phone: '9123456780',
    city: 'Nagpur',
    state: 'Maharashtra',
    placedOn: '2026-06-05',
    deliveryDate: '2026-06-09',
    itemCount: 15,
    amount: 40750,
    status: 'Processing',
    paymentStatus: 'Unpaid',
    salesChannel: 'Sales Rep Visit',
    shippingAddress: 'Sitabuldi, Nagpur, Maharashtra, 440012',
    notes: 'Awaiting payment confirmation before dispatch.',
    items: [
      { sku: 'QB-TRV-118', name: 'Compact Trolley Bag', quantity: 5, price: 3125 },
      { sku: 'QB-SCH-101', name: 'School Backpack Pro', quantity: 6, price: 1850 },
      { sku: 'QB-HND-302', name: 'Classic Handbag', quantity: 4, price: 1750 },
    ],
  },
]
